### PR TITLE
add ngstrefftz project

### PR DESCRIPTION
**Pull request by PaulSt**
Hi everyone!

I put together the implementation of Trefftz functions for the wave equation, trying to keep a similar style on the python side as you did. There are still many things to do, but maybe it would be cool to merge the projects? Let me know what you think!

Cheers,
Paul

### CODE REVIEW

**Comment by jayggg** [comment]
Hi Paul - 

Your code seems to add a significant additional dependency (boost), so  I am not prepared to merge it right now. If you can avoid this dependency please resubmit pull request, after also making trefftz a submodule of ngstents (so you can import from ngstents.trefftz analogous to ngstents.conslaw).

Thanks, -Jay

**Comment by PaulSt** [comment]
Hi Jay, 

thank you very much for the speedy feedback! Done and done, I hope it is better now. Let me know if there is anything else to improve!

Cheers, Paul

**Comment by jayggg** [comment]
Hi Paul - 
When compiling using Apple clang version 11.0.0 (clang-1100.0.33.12) I see a number of compile-time errors. 
  - Jay 

ngstents/src/trefftz/scalarmappedfe.hpp:89:10: note: 
      non-constexpr function 'round' cannot be used in a constant expression
                return round( tgamma(n+1) / (tgamma(k+1)*tgamma(n-k+1)) );

**Comment by PaulSt** [comment]
Hi Jay,
thanks for pointing that out! Curious what constexpr round function my compiler found to use at that point... I hope it works now! I tested with clang-12 and gcc-11 on linux, sadly I do not have an apple machine to test on. 
Bests, Paul

**Pull request merged**
